### ISSUE TITLE
Tetanus toxoid given to pregnant mothers is not reflecting in MOH710.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/report-scripts#54]
Tetanus toxoid given to pregnant mothers is not reflecting in MOH710.

Task
--------
Ensure all tetanus immunization given to pregnant mothers reflects in MOH710 report

**Comment by daugmaud** [comment]
These have been done, however, you need to update Hospital Core and MCH App before you can start counting this. Kindly pull the same and test
