### ISSUE TITLE
MCH Stores stock not displayed in MOH 710 reports

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/report-scripts#55]
MCH Stores stock not displayed in MOH 710 reports

Task
-------
Ensure all MCH stores stock is reflected in MOH 710 report

**Comment by daugmaud** [comment]
I can see the stock on the report, is it that they figures are wrong or, are there specific one that are missing, and if so, kindly note which ones

**Comment by pwanjiru** [comment]
Tested
