### ISSUE TITLE
In MOH 711, the value of ‘New ANC clients’ is that of ‘Re-Visit ANC clients’ and vice  versa.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/report-scripts#61]
In MOH 711, the value of ‘New ANC clients’ is that of ‘Re-Visit ANC clients’ and vice versa.

**Comment by daugmaud** [comment]
Script looks ok, kindly confirm by doing an actual test and see..

**Comment by pwanjiru** [comment]
-We still have the MOH 711 and 717 not recording ANC revisits that go through triage only.
this makes the No. of revisits to be incorrect.

**Comment by pwanjiru** [comment]
Fixed and verified
