### ISSUE TITLE
In MOH 711, ‘Mother counselled on infant feeding options’ is giving a value of 32 yet no  mother was given counselling on infant feeding.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/report-scripts#62]
In MOH 711, ‘Mother counselled on infant feeding options’ is giving a value of 32 yet no mother was given counselling on infant feeding.

**Comment by daugmaud** [comment]
Fixed the bug

**Comment by pwanjiru** [comment]
This has been fixed
