### ISSUE TITLE
MOH 717: We aren't getting the correct details of male and female patients due to UUIDs not captured correctly in the report templates.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/report-scripts#66]
MOH 717: We aren't getting the correct details of male and female patients due to UUIDs not captured correctly in the report templates.

**Comment by daugmaud** [comment]
Kindly expound on this. It's not clear @pwanjiru

**Comment by pwanjiru** [comment]
We have wrong UIDs on the report templates thus we cannot get correct details for males and females patients

**Comment by pwanjiru** [comment]
this will affect us when integrating to DHIS. UUIDs to be corrected
